### ISSUE TITLE
pygazebo drops large messages

### ISSUE THREAD

**Issue by jensanjo** [jpieper/pygazebo#1]
I want to use pygazebo to subscribe to images published by a gazebo plugin.
I found out that pygazebo does not respond to large messages.

The problem becomes visible when the message size is above 40.. 50 kB.

Below are two small programs that demonstrate the issue:
Run the subscriber (sub.py) in one terminal, and the publisher (pub.py) in another.

`$ python sub.py`

`$ python pub.py 10 50000`

The subscriber (sub.py):

```
from pygazebo.msg.gz_string_pb2 import GzString
import eventlet

def callback(data):
    message = GzString.FromString(data)
    print 'got message %s' % message.data[:4]

topic='/gazebo/default/test/request'
manager = pygazebo.Manager(('localhost', 11345))
sub = manager.subscribe(topic, 'gazebo.msgs.GzString', callback)

while True:
  eventlet.sleep(1)
```

And the publisher (pub.py):

```
import pygazebo
import sys
from pygazebo.msg.gz_string_pb2 import GzString
import time

n = 10
size = 1000
if len(sys.argv) > 2:
  n,size = map(int, sys.argv[1:3])

manager = pygazebo.Manager(('localhost', 11345))
topic = '/gazebo/default/test/request'
publisher = manager.advertise(topic, 'gazebo.msgs.GzString')

publisher.wait_for_listener()
for i in range(n):
  msg = GzString(data='%4d' % i  + ' '*(size-4))
  publisher.publish(msg)
  time.sleep(0.2)
```

**Comment by jensanjo** [comment]
I did a similar test with two standalone C++ programs using the gazebo transport library.
Then it works as expected.

**Comment by jpieper** [comment]
Thanks!  I think it should be fixed in 16e97e877f53405773c362b52de906f1de7a0e85.

Would you be willing to give it a try?

**Comment by jensanjo** [comment]
Great!   I will check it out.
Op 21 mrt. 2014 01:40 schreef "jpieper" notifications@github.com:

**Comment by jensanjo** [comment]
I confirm that the fix works fine.
Thanks a lot!

**Comment by jpieper** [comment]
Thanks for checking!
