### ISSUE TITLE
pygazebo and plugins

### ISSUE THREAD

**Issue by nashamri** [jpieper/pygazebo#14]
Hello there,

This might be a stupid question but I'm new to gazebo and I was following the "how to write a plugin" tutorial and I'm wondering if I can use pygazebo to write a plugin? 

Cheers!

**Comment by jpieper** [comment]
Sorry, but no.  pygazebo is intended to interact with gazebo over the network based publish subscribe system.  A gazebo plugin is software that runs within the gazebo process, and as far as I know needs to be written in C++ to use the existing gazebo APIs.
