### ISSUE TITLE
Callbacks performance

### ISSUE THREAD

**Issue by nashamri** [jpieper/pygazebo#16]
Hey all, happy holidays :)

I have a question which I'm not sure if this is the right place to ask about (if not, I'm sorry in advance).

In Gazebo, I have 2 boxes and a sphere that I'm controlling using a joystick and a point light. Also I have a subscriber to `/gazebo/default/physics/contacts`. In the callback I'm checking for physical contacts between the controlled sphere and one of the boxes, and when a collision happens, the point light turns on. Everything works fine except there is a ~2 seconds delay from when the collision happens till the light is turned on.

I think the reason for this delay is the amount of data sent from the topic (it was around ~30KB/s) which takes a while for the script to find the correct collision and respond by turning the point light.

So my question is, is there a better way to respond to events in pygazebo? (I'm not interested in all the collisions in my example, I just want one specific collision) or am I doing something totally wrong? (which is very plausible).

I'm using Gazebo 4.0 and pygazebo from the development branch.

Here is the callback:

``` python
def contacts_callback(data):
    message = pygazebo.msg.contacts_pb2.Contacts.FromString(data)
    if message.contact:
        for contact in message.contact:
            col2 = contact.collision2.split("::")[0]
            if col2 == "unit_box_1":
                turn_light_on()
            elif col2 == "unit_box_2":
                turn_light_off()
```

Thanks!

**Comment by virtuald** [comment]
I've had problems similar to what you're describing in gazebo 3.x. At first, my data is in sync, and then after a few seconds it gets out of sync. My investigation into this showed that there was probably too much data being passed around, and the python code couldn't keep up with it, so it fell behind.

**Comment by jpieper** [comment]
Without seeing the full source (especially the implementation of turn_light_on and turn_light_off), it is hard to tell.  pygazebo is never going to be that performant.  I have used it to control 14 servo actuators open loop in real time at least.  You might try using a python profiler to see if you are spending a lot of time in your code or in pygazebo.

**Comment by jpieper** [comment]
Closing due to lack of reply.
