### ISSUE TITLE
Correct README file

### ISSUE THREAD

**Issue by kunaltyagi** [jpieper/pygazebo#2]
The code in README files is incorrect.
By using `$ [sudo] pip install pygazebo` and then running the sample code, the following error is reported:
- pygazebo not found
  
  Correct, since only Manager is being imported
- Manager has no connections
  
  Again, no port is being provided

The code used was picked up from branch Master

**Comment by jpieper** [comment]
Yes, the README on master is missing an "import pygazebo.msg"

If you run gazebo in the default way, you should not need to specify a port, as pygazebo uses the same default port that gazebo does.  Did you start the gazebo server before starting pygazebo?  What exact error message did you see?

**Comment by jpieper** [comment]
The readme was updated as part of the switch from eventlet to trollius.  Release on master as of 9c977703be5c04fe931e7ec522fb7aa1e6bbe05e
