### ISSUE TITLE
Compatibility with Gazebo 1.9?

### ISSUE THREAD

**Issue by RDaneelOlivav** [jpieper/pygazebo#21]
Is there a way of using it with Gazebo 1.9?

**Comment by jpieper** [comment]
Have you tried?  I suspect it might just work out of the box.

**Comment by RDaneelOlivav** [comment]
File "/usr/local/lib/python2.7/dist-packages/trollius-1.0.4-py2.7.egg/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/trollius-1.0.4-py2.7.egg/trollius/futures.py", line 287, in result
    raise self._exception
pygazebo.pygazebo.ParseError: Unsupported gazebo version: gazebo 1.9

Gives this error, any ideas?

**Comment by jpieper** [comment]
Yes, well, you'll have to disable that check before you can see if it works.

Look in the _handle_version_init method, and change the 2.2 to something like 1.0 and then see if you are able to communicate correctly.  I have just only tested with 2.2 and newer so far.

**Comment by RDaneelOlivav** [comment]
Worked perfectly ;) Thanks @jpieper

**Comment by jpieper** [comment]
Fixed in 3eaac84f6f21dd01ba6361b0c53fb7533cc53e69
