### ISSUE TITLE
Possible race condition?

### ISSUE THREAD

**Issue by Skylion007** [jpieper/pygazebo#24]
So I am wrote a program to apply some joint PIDs when the server start. However, it only works when I put .sleep between successive Trollius calls and when I put Trollius sleep of .1 BEFORE the first publisher.message. Any idea why this works only in this configuration? I would like to note that it also works if you shove everything into one giant event loop, but otherwise it does not work. Any idea what could be causing it? I fear it might be a race condition on Trollius

Here is the code:

```
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 14 13:27:48 2015

@author: skylion
"""
import trollius #NOTE: Trollius requires protobuffer from Google
from trollius import From

import pygazebo
import pygazebo.msg.joint_cmd_pb2
import time 
import popupcad
from lxml import etree
import subprocess
import os

try:
    import itertools.izip as zip
except ImportError:
    pass


def apply_joint_pos(world_name, robot_name, joint_names, poses, duration=0):
    wait_net_service('localhost', 11345)
    time.sleep(1.0)
    print("Net serviced detected. Proceeding")

    @trollius.coroutine
    def joint_pose_loop(world_name, robot_name, joint_name, pose, duration):
        manager = yield From(pygazebo.connect())
        print("connected")


        publisher = yield From(
            manager.advertise('/gazebo/' + world_name + '/' + robot_name + '/joint_cmd',
                              'gazebo.msgs.JointCmd'))

        message = pygazebo.msg.joint_cmd_pb2.JointCmd()
        message.name = robot_name + '::' + joint_name #format should be: name_of_robot + '::name_of_joint'
        print(message.position.target)
        message.position.target = pose
        print(message.position.target)
       # message.force = pose
        try:
            yield From(trollius.sleep(0.1))            
            yield From(publisher.publish(message))  
        except :
            print("ugh oh")
            pass

        print("Connection closed")

    def loop_in_thread(loop, tasks):
        trollius.set_event_loop(loop)
        loop.run_until_complete(trollius.wait(tasks))

    tasks = []
    for joint_name, pose in zip(joint_names, poses):
        tasks.append(trollius.Task(joint_pose_loop(world_name, robot_name, joint_name, pose, duration)))

    loop = trollius.get_event_loop()        
    loop.run_until_complete(trollius.wait(tasks))
        #TODO either integrate with PyGazebo or clean up, maybe with sub processes
    #This is a Sandbox Nightmare. Poor Coding practices


def wait_net_service(server, port, timeout=None):
    """ Wait for network service to appear 
        @param timeout: in seconds, if None or 0 wait forever
        @return: True of False, if timeout is None may return only True or
                 throw unhandled network exception
    """
    import socket
    import errno

    s = socket.socket()
    if timeout:
        from time import time as now
        # time module is needed to calc timeout shared between two exceptions
        end = now() + timeout

    while True:   
        try:
            if timeout:
                next_timeout = end - now()
                if next_timeout < 0:
                    return False
                else:
                    s.settimeout(next_timeout)
            s.connect((server, port))
        except socket.timeout as err:
            # this exception occurs only if timeout is set
            if timeout:
                return False

        except socket.error as err:
            # catch timeout exception from underlying network library
            # this one is different from socket.timeout
            if type(err.args) != tuple or (err[0] != errno.ETIMEDOUT and err[0] != errno.ECONNREFUSED):
                raise err
        else:
            s.close()
            return True

world_name='world'
robot_name='default_body'
joint_names=['hingejoint0', 'hingejoint1', 'hingejoint2', 'hingejoint3', 'hingejoint4', 'hingejoint5', 'hingejoint6', 'hingejoint7', 'hingejoint8']

apply_joint_pos(world_name, robot_name,['hingejoint1'], [9])
apply_joint_pos(world_name, robot_name,['hingejoint2'], [-9])
apply_joint_pos(world_name, robot_name,['hingejoint3'], [-7])
apply_joint_pos(world_name, robot_name,['hingejoint4','hingejoint5'], [-10,-10])
apply_joint_pos(world_name, robot_name,['hingejoint0'], [-21])
apply_joint_pos(world_name, robot_name,['hingejoint4','hingejoint5'], [-15,-15])
apply_joint_pos(world_name, robot_name,['hingejoint3'], [-12])
```

**Comment by jpieper** [comment]
Well, there are a number of possible problems with the code as you have written it.

For one, gazebo (and thus pygazebo), isn't really intended to operate in the mode where you make a brand new server connection for every command you want to send.  The intended mode of operation is that you make a single connection, advertise something once, then send multiple values on that publication over time.  I don't think pygazebo has any startup races when used according to the API, but gazebo itself sure may.  That said, I don't think you are likely hitting any here.

Secondly, if you want to ensure that there is a listener before you write to a topic, pygazebo's Publisher class provides a "wait_for_listener" method you can use to ensure that there is indeed someone listening to your publication before you send.  (I suspect this will solve your immediate problem).

Third, trollius, (and the python3 asyncio it is a port of), has a normal operating mode where you start the event loop once, and do all of your logic as part of a coroutine or callback.  I don't think you are experiencing any race conditions here in trollius, but you will find things in general harder to use with the model you've settled upon.

**Comment by Skylion007** [comment]
What type of model do you recommend for the situation I have setup where I want to send sequential commands? I am having the user specify it and I would rather not have the user need to learn about the intricacies of Gazebo topics?

Also thank you, solution number 2 worked perfectly and I added an additional wait function in a separate pull request that users of the repository may find helpful.

I do still occasionally get a malformed header exception. How should I deal with that btw?

**Comment by jpieper** [comment]
If you want to send sequential commands, the preferred model is to create a single coroutine, which

 1) makes a connection
 2) makes a publication
 3) publishes a new value
 4) optionally sleeps
 5) loops to step 3

Can you provide more information on the malformed header exception you are seeing?

**Comment by Skylion007** [comment]
Well ever since I did the wait_for_listener trick, that issue has gone away. The only issue I have with looping like that is that I do not want to loop for the whole time you see. I may only want to apply force and then another force in which case, it's rather annoying for the end user to code a single loop statement that will handle all possible time stamps or use some the intricate features of asyncio/trollius to code that in. This is only exacerbated the fact that remove() on publisher and subscriber is currently not implemented.

**Comment by virtuald** [comment]
@Skylion007 I suspect that if you don't want your users to have to use asyncio/trollius, your best bet should run a trollius ioloop in a separate thread, and provide an api that uses queues/etc to communicate with the trollius thread. It'll be a bit clunky, but should work fine.

You would need to call `call_soon_threadsafe` to do operations on the asyncio thread from a different thread, and then your asyncio code could communicate with the other threads via a queue or a `concurrent.Future` object (not the asyncio version, however!).

**Comment by jpieper** [comment]
Alright, I'm going to close this one now, since the appropriate use case is to shove everything into one asyncio loop, either in the application itself, or as virtuald described, in a separate thread which the primary thread interacts with.
