### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by qwedaq** [jpieper/pygazebo#38]
Hello, I installed pygazebo==3.0.0.2014.1 using pip install pygazebo. When I try to run the script it throws an import error. I am attaching below the error. 

System:
Ubuntu 18.04
ROS2
Gazebo 9
![Screenshot from 2020-11-09 16-30-56](https://user-images.githubusercontent.com/25226325/98561647-6c7ed180-22a9-11eb-8245-39e16c08eded.png)

**Comment by jpieper** [comment]
Thanks for reporting a problem!  You may have noticed that pygazebo hasn't seen any activity in some time.  You're more than welcome to try and resolve issues yourself, but I'm not currently working on it.
